### ISSUE TITLE
Refactor: InputEvent -> Action

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#103]
This involves replacing:

InputEvent -> Action
input_event -> action

What else? Please provide links in the comments (including to documentation)

**Comment by 0dm** [comment]
replaced "input_events" with "actions" : 73 occurrences in 8 files
replaced "input_event" with "action" : 78 occurrences in 11 files (ignore alembic)
replaced "InputEvent" with "Action" : 25 occurrences in 11 files
added alembic revision

- recording ✅
- visualize ✅
- replay ✅
