### ISSUE TITLE
Incorrect Truncation of Prompt in LLMReplayStrategyMixin class.

### ISSUE THREAD

**Issue by FFFiend** [MLDSAI/OpenAdapt#127]
As the title suggests, the prompt string is being truncated incorrectly inside the ```get_completion``` method in the ```llm_mixin.py``` file. The first [0, max_input_size-1] characters must be fetched but instead the characters in the range [max_input_size, len(prompt)-1] are being fetched.

**Comment by abrichr** [comment]
Thanks @FFFiend ! I believe we want `[-max_input_size:]` as a first order implementation, PR here: https://github.com/MLDSAI/OpenAdapt/pull/129/files

`[0, max_input_size-1]` would not keep the most recent data.

**Comment by FFFiend** [comment]
Oh I see, I'm a bit confused though: What are the benefits of keeping truncating the beginning of the input as opposed to the end? Inputs don't have be symmetric in general (the average English sentence isn't) so I'm curious about how one decides. 

I'm an ML novice so all of this seems like it's helpful to know, sorry if this issue was nitpicky :D I also posted an updated comment over at  #27 if you could take a look :)

**Comment by abrichr** [comment]
The most relevant context will be at the end. Ideally we have all of the context, but if we have to truncate, and without any additional information, it's best to truncate at the beginning since that context is older.
