### ISSUE TITLE
SQLite database is locked

### ISSUE THREAD

**Issue by ahmetutku** [MLDSAI/OpenAdapt#130]
Hello, when I run the Python code involving the line "input_events = get_events(recording, process=PROCESS_EVENTS, meta=meta)" I get the error: "sqlite3.OperationalError: database is locked" & "sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) database is locked. " However, the same line of code is being run in visualize.py. I wanted to see if anybody had a similar issue. If so how did they fix it?

**Comment by ahmetutku** [comment]
running it with -m fixed the problem

**Comment by abrichr** [comment]
This suggests that you may have two processes writing the database at the same time.

Perhaps you have something running the background; try killing it with `pkill -f python`.

(In the future please format your comment as per https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
