### ISSUE TITLE
Fix atomacos in requirements.txt

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#206]
![image](https://github.com/MLDSAI/OpenAdapt/assets/774615/bde3e79e-f4b7-4f46-8e66-1bfba51a30ee)

Solution:

Modify [this line](https://github.com/MLDSAI/OpenAdapt/blob/main/requirements.txt#L3):

```
-e git+https://github.com/abrichr/atomacos.git; sys_platform == 'darwin'
```

To:

```
-e git+https://github.com/abrichr/atomacos.git#atomacos ; sys_platform == 'darwin'
```

**Comment by KrishPatel13** [comment]
After fixing that, while pip install -r requiements.txt --no-cache-dir

I encountered this:

<img width="720" alt="image" src="https://github.com/MLDSAI/OpenAdapt/assets/65433817/803f7e44-0c3a-482c-823a-345f4a4a1322">


I have tried: https://github.com/MLDSAI/OpenAdapt/issues/40#issuecomment-1528350805

I have latest setuptools, wheel, pip libraries.

**Comment by KrishPatel13** [comment]
This is my current requirements.txt:

```
alembic==1.8.1
ascii_magic==2.3.0
-e git+https://github.com/abrichr/atomacos.git#egg=atomacos ; sys_platform == 'darwin'
bokeh==2.4.3
clipboard==0.0.4
deepdiff[optimize]==6.3.0
dictalchemy3==1.0.0
fire==0.4.0
ipdb==0.13.11
loguru==0.6.0
matplotlib==3.6.2
mss==6.1.0
openai==0.27.5
pandas==2.0.0
pygetwindow==0.0.9; sys_platform == 'win32'
pyinstaller
setuptools-lint
sphinx
python-dotenv==1.0.0
pywin32==306; sys_platform == 'win32'
-e git+https://github.com/abrichr/pynput.git#egg=pynput
pytest==7.1.3
rapidocr-onnxruntime==1.2.3
scikit-learn==1.2.2
scipy==1.9.3
sqlalchemy==1.4.43
tiktoken==0.4.0
torch==2.0.0
tqdm==4.64.0
transformers==4.28.1
```

**Comment by KrishPatel13** [comment]
I am using Windows OS

**Comment by KrishPatel13** [comment]
> After fixing that, while pip install -r requiements.txt --no-cache-dir
> 
> I encountered this:
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/65433817/242030694-803f7e44-0c3a-482c-823a-345f4a4a1322.png">
> I have tried: [#40 (comment)](https://github.com/MLDSAI/OpenAdapt/issues/40#issuecomment-1528350805)
> 
> I have latest setuptools, wheel, pip libraries.

Looks like it is installing atomacos even if my os is windows that means the test condition
 sys_platform == 'darwin' is failing or not executing

**Comment by KrishPatel13** [comment]
A simple solutions that fixed it is:

Solution:

Modify [this line](https://github.com/MLDSAI/OpenAdapt/blob/main/requirements.txt#L3):

To:

`git+https://github.com/abrichr/atomacos.git; sys_platform == 'darwin'`

But will this work for Mac OS as well ?

If yes, then I can make a PR.

**Comment by abrichr** [comment]
If you recall, we needed to add #atomacos to this line in order for it not to fail on your machine.

The fact that it was failing is itself an issue, since pip should know not to install it due to the sys_platform.

Can you please figure out how to specify #atomacos for sys_platform == 'darwin'?

**Comment by KrishPatel13** [comment]
I added #atomacos
`-e git+https://github.com/abrichr/atomacos.git#atomacos ; sys_platform == 'darwin'`

On installing even this gave error as below:
`ERROR: Could not detect requirement name for 'git+https://github.com/abrichr/atomacos.git#atomacos', please specify one with #egg=your_package_name`

On changing to: 
`-e git+https://github.com/abrichr/atomacos.git#egg=atomacos ; sys_platform == 'darwin'`

This gave the error:
```
Collecting pyobjc-core>=3.0.4 (from atomacos->-r .\requirements.txt (line 3))
  Downloading pyobjc-core-9.1.1.tar.gz (896 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 896.1/896.1 kB 2.4 MB/s eta 0:00:00        
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.   
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by abrichr** [comment]
Thanks @KrishPatel13 ! Can we keep the `-e`?

**Comment by KrishPatel13** [comment]
With -e 

as I said it ignores the sys_platform='darwin'. So it tries to install that too for windows and thus resukts in the error. 

I have researced online no where I can find an error similar to this where they have used -e and they got similar errors with the platform consitionals.

**Comment by KrishPatel13** [comment]
If [this PR](https://github.com/MLDSAI/OpenAdapt/pull/211) is closed with merging, then we can close this issue.
