### ISSUE TITLE
Implement Video Scrubbing script

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#284]
### Feature request

We would like to be able to scrub video files (e.g. MP4) showing PII/PHI.

This task involves creating a script under `/scripts/scrub.py` that takes a path to a media file (e.g. MP4, PNG, PDF), and generates a scrubbed version of that file.

For now let's just implement .mp4, and leave other formats as TODOs.

### Motivation

https://github.com/OpenAdaptAI/web/issues/22

**Comment by KrishPatel13** [comment]
For this should we move the current `openadapt/scrub.py` module to `openadapt/scripts/scrub.py` and then edit to accomplish this task ? 

So rather we should make a new file ?

**Comment by abrichr** [comment]
We should not move the existing `scrub.py`. This is a separate file that will import `openadapt.scrub`.

**Comment by KrishPatel13** [comment]
@abrichr  Noted!

**Comment by KrishPatel13** [comment]
@abrichr 
https://dev.to/aws-heroes/blur-personal-identifiable-information-pii-in-text-images-and-videos-12j4

I found the above article and it uses AWS to detect PII and blur them in video.

Should I try to use this approach ?
