### ISSUE TITLE
Explore LLMs to Load on CPU for Offline Usage

### ISSUE THREAD

**Issue by FFFiend** [MLDSAI/OpenAdapt#286]
### Feature request

A really good example is https://github.com/ggerganov/llama.cpp 
https://finbarr.ca/how-is-llama-cpp-possible/ good supplemental read 
### Motivation

fizzbuzz

**Comment by FFFiend** [comment]
LLama.cpp seems super easy to load on mac, and the only requirement is enough disk space and RAM. Question now is: how do we want to integrate it into the repo?

**Comment by abrichr** [comment]
We want to be able to fall back on an LLM with no internet access we can load on anyone's computer that doesn't have a hard GPU requirement.
