### ISSUE TITLE
[Bug]: Tesseract not installed

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#308]
### Describe the bug

Running tests fails on a machine that does not already have tesseract installed.

### To Reproduce

https://github.com/MLDSAI/OpenAdapt/issues/295#issuecomment-1602616550

**Comment by KrishPatel13** [comment]
the blocker for Windows is that there is on 1 line installation for Windows.
We have to download the binary file and then manual add the dir. to PATH variable.

**Comment by KrishPatel13** [comment]
<img width="644" alt="image" src="https://github.com/MLDSAI/OpenAdapt/assets/65433817/7f73459c-394a-4175-9d7a-da13aeda3c3a">


I am encountering this strange error for Windows installation

**Comment by dianzrong** [comment]
@0dm I have currently implemented installing homebrew in the install script and tesseract

**Comment by KrishPatel13** [comment]
@abrichr The Powershell script is ready to be merged
