### ISSUE TITLE
Bug: Decord for Mac 

### ISSUE THREAD

**Issue by ahmetutku** [MLDSAI/OpenAdapt#38]
Hello, I was trying to install MiniGPT 4, for that I had the run the command "conda env create -f environment.yml". This tried to install decord which gave me the error: "
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement decord==0.6.0 (from versions: none)
ERROR: No matching distribution found for decord==0.6.0

failed

CondaEnvException: Pip failed

(base) ahmethamamcioglu@Ahmet-MacBook-Air MiniGPT-4 % pip install --upgrade pip

Requirement already satisfied: pip in /Users/ahmethamamcioglu/anaconda3/lib/python3.10/site-packages (22.3.1)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 14.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.1.2
(base) ahmethamamcioglu@Ahmet-MacBook-Air MiniGPT-4 % pip install decord==0.6.0

ERROR: Could not find a version that satisfies the requirement decord==0.6.0 (from versions: none)
ERROR: No matching distribution found for decord==0.6.0
(base) ahmethamamcioglu@Ahmet-MacBook-Air MiniGPT-4 % pip install decord

ERROR: Could not find a version that satisfies the requirement decord (from versions: none)
ERROR: No matching distribution found for decord" I also tried to install it separately but it did not work.  I found this thread online: https://github.com/dmlc/decord/issues/213 which did not have a solution for the same problem. I was wondering if anybody could help?

**Comment by abrichr** [comment]
Hi @ahmetutku ,

There appears to be an issue and solution in the MiniGPT-4 repo: https://github.com/Vision-CAIR/MiniGPT-4/issues/64#issuecomment-1524987088

Can you please try it and let us know if it resolves the issue? Than you!

**Comment by abrichr** [comment]
@ahmetutku any update on this?

**Comment by ahmetutku** [comment]
@abrichr Using the comment I was able to download Decord. So it is solved; thank you!
