### ISSUE TITLE
Implement installation script for complete beginners

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#83]
In order to support use cases for non-technical audiences, we need some extremely simple "Getting started with OpenAdapt for Complete Beginners. e.g:

1. Download and install Git: https://git-scm.com/download/
2. Download and install Python: https://www.python.org/downloads/

Mac:
3. press CMD+Space, type "terminal" and press Enter
4. copy and paste the following command into the terminal, then press Enter:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/OpenAdaptAI/install/HEAD/install_puterbot.sh)"
```

Windows:
3. press WINKEY, type "powershell", and press Enter
4. copy and paste the following command into the terminal, then press Enter:
```
powershell -ExecutionPolicy Bypass -Command "iwr -UseBasicParsing -Uri 'https://raw.githubusercontent.com/OpenAdaptAI/install/HEAD/install_puterbot.ps1' | Invoke-Expression"
```

(The contents of these instructions will be placed immediately below the email registration on https://openadapt.ai)

This task involves:
- Implementing `install_puterbot.sh` and `install_puterbot.ps1` (see https://github.com/MLDSAI/puterbot#install)
- Optional: modifying the implementation to automatically determine whether Git and Python3.10 are already installed, and download and install them if necessary

**Comment by apgorton** [comment]
This is being done in https://github.com/OpenAdaptAI/install which will be linked with this later. Sorry for the confusion @KrishPatel13
