### ISSUE TITLE
Save perf_q to database

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#85]
This task involves creating a model and saving events from `perf_q` in `record.py`:

https://github.com/MLDSAI/puterbot/blob/main/puterbot/record.py#LL591C10-L591C10

**Comment by abrichr** [comment]
@apgorton thank you for finding the source of https://github.com/MLDSAI/OpenAdapt/issues/93 ! I believe this is the solution. Let's treat performance events just like Screenshots/InputEvents/WindowEvents and save them to a new table. That way there won't be any special queue left over when everything is shutting down and that problem goes away.

What do you think?

**Comment by apgorton** [comment]
I think this approach would address https://github.com/MLDSAI/OpenAdapt/issues/93 and is a good way to do that while implementing this one. I'll make the changes.
