### ISSUE TITLE
Record hanging on windows instead of ending

### ISSUE THREAD

**Issue by apgorton** [MLDSAI/OpenAdapt#93]
Windows 10

Sometimes on windows record.py will hang after Ctrl-C with python processes left running.

**Comment by abrichr** [comment]
Confirmed on MacOS

@apgorton any ideas on approaches? I believe we ruled out logging. Could it be the `pynput` listeners are not terminating?

I think the next course of action will be to add copious `logger.trace` statements, what do you think?
